reachc: error: REACH_ERR_EVAL106

 ./Err_Token_DynamicRef.rsh:8:52:application

 8|   Foldable_forEach(atoks, (tok) => transfer(balance(tok), tok).to(Who));

    Token reference based on dynamic computation, which Reach cannot track, yet.

Trace:
  in "f" from (./Err_Token_DynamicRef.rsh:8:33:function exp) at (reach standard library:108:40:application)
  in [unknown function] from (reach standard library:108:36:function exp) at (reach standard library:108:21:application)
  in "Foldable_forEach" from (reach standard library:108:10:function exp) at (./Err_Token_DynamicRef.rsh:8:19:application)
  in "closeToks" from (./Err_Token_DynamicRef.rsh:4:1:function exp) at (./Err_Token_DynamicRef.rsh:27:14:application)

For further explanation of this error, see: docs.reach.sh/ref-error-codes.html/#%28tech._REACH_ERR_EVAL106%29

